language: rust
sudo: required
dist: trusty
addons:
  apt:
    packages:
      - libssl-dev
cache: cargo

rust:
  - stable
  - beta
  - nightly

matrix:
  allow_failures:
    - rust: nightly

before_cache: |
  if [[ "$TRAVIS_RUST_VERSION" == beta ]]; then
    cargo install cargo-tarpaulin -f
  fi

script:
  - cargo test --verbose
  - cargo test --all-features --verbose

after_success: |
  if [[ "$TRAVIS_RUST_VERSION" == beta ]]; then
    cargo tarpaulin --out Xml --all --all-features --ignore-tests --verbose
    bash <(curl -s https://codecov.io/bash)
  fi
