language: rust

rust:
  - stable
  - beta
  - nightly

os:
  - linux

dist: trusty
addons:
  apt:
    packages:
      - libssl-dev

matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true

cache: cargo

before_cache: |
  rm -rf "$TRAVIS_HOME/.cargo/registry/src"
  if [[ "$TRAVIS_RUST_VERSION" == beta && "$TRAVIS_OS_NAME" == "linux" ]]; then
    cargo install cargo-tarpaulin -f
  fi

script:
  - cargo build --lib --all-features --verbose
  - cargo build --all --all-targets --verbose
  - cargo test --all --verbose

after_success: |
  if [[ "$TRAVIS_RUST_VERSION" == beta && "$TRAVIS_OS_NAME" == "linux" ]]; then
    cargo tarpaulin --out Xml --ignore-tests --verbose
    bash <(curl -s https://codecov.io/bash)
  fi
